[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
fs_permissions = [
  { access = "read", path = "./script/target" },
  { access = "write", path = "./script/target" }
]

remappings = [
    '@openzeppelin/ = lib/openzeppelin-contracts/contracts/',
    'forge-std/ = lib/forge-std/src/',
    'murky/ = lib/murky/src/'
]




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
